# .a3.yml — PythonFromScratch configuration
# See: https://github.com/thehalleyyoung/PythonFromScratch

analysis:
  interprocedural: true
  kitchensink: true
  dse-verify: true
  min-confidence: 0.3
  deduplicate: true
  no-intent-filter: true
  max-dse-steps: 100

ci:
  fail-on-new-bugs: true
  baseline-file: .a3-baseline.json
  llm-triage: true
  llm-model: gpt-4o
  llm-provider: github
  sarif-upload: true

scan:
  exclude:
    - "tests/**"
    - "test/**"
    - "**/test_*.py"
    - "docs/**"
    - "examples/**"
    - "setup.py"
    - "conftest.py"
  include:
    - "**/*.py"
